//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeOdevi
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparisler
    {
        public int siparisId { get; set; }
        public int urunId { get; set; }
        public string durum { get; set; }
        public string adres { get; set; }
        public string soyad { get; set; }
        public string ad { get; set; }
        public string telNo { get; set; }
        public string eMail { get; set; }
    
        public virtual urunler urunler { get; set; }
    }
}
